#ifndef MCOMPETDATA_GLOBAL_H
#define MCOMPETDATA_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(MCOMPETDATA_LIBRARY)
#  define MCOMPETDATASHARED_EXPORT Q_DECL_EXPORT
#else
#  define MCOMPETDATASHARED_EXPORT Q_DECL_IMPORT
#endif

#endif // MCOMPETDATA_GLOBAL_H
